# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04416fbe3314c28a7aca4b75192bdff3dee3f0d11c9cc2875f320ee4abde0431090e3e34b79be89b79952e3eb58a5f4f1043e866b35f49c6b3640a7061acb236

test:
  secret_key_base: 6d3cbb188bfed4c59a817b64274234e4d2f9a49285b0a8de9fd1646afab57013d03439ad162c8f534cf672066f5dc138732b26350cb1bac2c59565c1139a98aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
